---
- name: Create application directory
  file:
    path: '{{ dest_dir }}'
    state: directory

- name: Copy Docker files
  copy:
    src: "{{ source_dir }}/{{ item.src }}"
    dest: "{{ dest_dir }}/{{ item.dest }}"
  with_items:
    - { src: 'docker-compose.prod.yml', dest: 'docker-compose.yml' }
    - { src: 'Dockerfile', dest: 'Dockerfile' }

- name: Copy application files
  synchronize:
    src: '{{ local_app_dir }}/'
    dest: '{{ dest_dir }}'
    delete: yes
    rsync_opts:
      - '--exclude=node_modules'
      - '--exclude=.git'
      - '--exclude=.gitignore'
  delegate_to: localhost

- name: Rebuild and start Docker Compose services
  command:
    cmd: docker compose -f {{ dest_dir }}/docker-compose.yml up -d --build
  args:
    chdir: '{{ dest_dir }}'
