---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install prerequisites
  apt:
    name:
      - curl
      - ca-certificates
      - gnupg
    state: present

- name: Add PostgreSQL repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present
    filename: pgdg

- name: Update apt cache again
  apt:
    update_cache: yes

- name: Install basic packages and PostgreSQL client
  apt:
    name:
      - curl
      - git
      - vim
      - postgresql-client
    state: present
