- name: Install latest version of Docker
  apt:
    name: docker.io
    state: latest

- name: Install Docker Compose plugin
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
    dest: "/usr/local/lib/docker/cli-plugins/docker-compose"
    mode: '0755'
  become: yes
